name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  MONGODB_CONNECTION: ${{ secrets.MONGODB_CONNECTION_STRING }}
  MONGODB_TEST_CONNECTION: ${{ secrets.MONGODB_TEST_CONNECTION_STRING }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test